[theme]
primaryColor       = "#EE7015"
backgroundColor    = "#FFFFFF"
secondaryBackgroundColor = "#EFEEEA"
textColor          = "#0A0909"
font               = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
